[build]
    functions = "functions"

[functions]
    directory = "functions"
    included_files = ["data.json"]

[[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/apis/:splat"