[build]
    functions = "functions"

[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/**"]

[[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/apis/:splat"