[build]
    functions = "functions"
    publish = "public"

[functions]
    external_node_modules = ["express", "ejs"]
    node_bundler = "esbuild"
    included_files = ["views/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
